@startuml global_usecase
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

skinparam usecase {
    BackgroundColor White
    BorderColor #2B3A4A
    ArrowColor #2B3A4A
    FontSize 12
    FontName Arial
}

skinparam actor {
    BackgroundColor White
    BorderColor #2B3A4A
    FontColor #1E1E2D
    FontSize 12
    FontName Arial
    FontStyle bold
}

skinparam rectangle {
    BackgroundColor White
    BorderColor #2B3A4A
    FontSize 15
    FontName Arial
    FontStyle bold
    FontColor #1E1E2D
}

skinparam arrow {
    Color #2B3A4A
    FontName Arial
    FontSize 11
}

actor "Opérateur" as OPE
actor "Administrateur" as ADM

rectangle "Plateforme Nexora" {
    usecase "S'authentifier" as UC0
    usecase "Mettre à jour l'état de production" as UC1
    usecase "Saisir un mouvement de stock" as UC2
    usecase "Gérer les machines d'atelier" as UC3
    usecase "Planifier les ordres de production" as UC4
    usecase "Suivre le rendement (TRG)" as UC5
    usecase "Consulter les prévisions d'IA" as UC6
    usecase "Gérer les comptes utilisateurs" as UC7
    usecase "Gérer les permissions (RBAC)" as UC8
}

' Associations Opérateur
OPE --> UC1
OPE --> UC2

' Associations Administrateur
ADM --> UC3
ADM --> UC4
ADM --> UC5
ADM --> UC6
ADM --> UC7
ADM --> UC8

' Relations d'inclusion
UC1 ..> UC0 : <<include>>
UC2 ..> UC0 : <<include>>
UC3 ..> UC0 : <<include>>
UC4 ..> UC0 : <<include>>
UC5 ..> UC0 : <<include>>
UC6 ..> UC0 : <<include>>
UC7 ..> UC0 : <<include>>
UC8 ..> UC0 : <<include>>
@enduml